In [267]:
import pandas as pd


In [268]:
d=pd.read_csv("500_Person_Gender_Height_Weight_Index.csv")

In [269]:
d.head()

Gender  Height  Weight  Index
0    Male     174      96      4
1    Male     189      87      2
2  Female     185     110      4
3  Female     195     104      3
4    Male     149      61      3

In [270]:
d['Height']=d['Height']*0.0328

In [271]:
d['Height']=d['Height'].round(decimals=1)

In [272]:
d.head()

Gender  Height  Weight  Index
0    Male     5.7      96      4
1    Male     6.2      87      2
2  Female     6.1     110      4
3  Female     6.4     104      3
4    Male     4.9      61      3

In [273]:
d.isnull().sum()

Gender    0
Height    0
Weight    0
Index     0
dtype: int64

In [274]:
y=d['Index']

In [275]:
y.head()

0    4
1    2
2    4
3    3
4    3
Name: Index, dtype: int64

In [276]:
d=d.drop('Index',axis=1)

In [277]:
d.head()

Gender  Height  Weight
0    Male     5.7      96
1    Male     6.2      87
2  Female     6.1     110
3  Female     6.4     104
4    Male     4.9      61

In [278]:
gender=pd.get_dummies(d['Gender'],drop_first=True)

In [279]:
gender.head()

Male
0     1
1     1
2     0
3     0
4     1

In [280]:
d=d.drop(['Gender'],axis=1)

In [281]:
X=pd.concat([d,gender], axis=1)

In [282]:
X.head()

Height  Weight  Male
0     5.7      96     1
1     6.2      87     1
2     6.1     110     0
3     6.4     104     0
4     4.9      61     1

In [283]:
X.shape

(1691, 3)

In [284]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=.3,random_state=0)

In [285]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [286]:
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [287]:
X_train

array([[-1.83024937, -0.79591426,  1.05296458],
       [-1.08658287,  1.60800681, -0.94969956],
       [-0.71474963,  1.02243629,  1.05296458],
       ...,
       [-0.15699975,  1.05325579, -0.94969956],
       [-1.64433275, -0.54935825,  1.05296458],
       [ 1.33033324,  0.06703176, -0.94969956]])

In [288]:
X_test

array([[-0.71474963,  1.3306313 , -0.94969956],
       [ 0.77258337, -0.67263626, -0.94969956],
       [-0.71474963,  0.43686577,  1.05296458],
       ...,
       [-0.90066625,  1.4539093 , -0.94969956],
       [ 0.40075012,  0.49850478, -0.94969956],
       [ 1.33033324,  0.06703176, -0.94969956]])

In [289]:
X_train.shape

(1183, 3)

In [290]:
from sklearn.ensemble import RandomForestRegressor
model=RandomForestClassifier(n_estimators=79)

<IPython.core.display.Javascript object>

In [291]:
model.fit(X_train,y_train)

RandomForestClassifier(n_estimators=79)

In [292]:
model.score(X_test,y_test)

0.9940944881889764

In [293]:
y_pred=model.predict(X_test)


In [294]:
y_pred

array([5, 3, 5, 5, 5, 5, 5, 4, 4, 4, 4, 2, 4, 5, 3, 1, 4, 3, 2, 2, 3, 1,
       5, 4, 5, 5, 5, 5, 4, 5, 5, 2, 4, 4, 3, 5, 3, 4, 5, 3, 3, 5, 4, 4,
       3, 3, 1, 5, 1, 3, 5, 5, 5, 4, 3, 5, 4, 5, 4, 4, 5, 4, 5, 2, 5, 4,
       4, 2, 5, 5, 5, 5, 5, 5, 4, 3, 5, 4, 2, 4, 5, 4, 4, 5, 4, 5, 2, 5,
       3, 1, 5, 5, 3, 5, 5, 5, 5, 4, 3, 5, 2, 5, 4, 4, 5, 1, 3, 2, 5, 2,
       5, 3, 5, 4, 5, 5, 2, 5, 1, 5, 1, 5, 5, 3, 5, 3, 3, 2, 2, 1, 3, 5,
       0, 4, 5, 2, 4, 4, 4, 4, 1, 5, 5, 5, 3, 5, 5, 3, 4, 5, 3, 2, 4, 5,
       4, 5, 5, 3, 2, 5, 5, 4, 3, 5, 4, 1, 4, 2, 5, 4, 0, 5, 3, 0, 4, 3,
       2, 5, 4, 2, 5, 5, 3, 5, 5, 0, 5, 5, 4, 3, 4, 4, 3, 1, 4, 2, 5, 5,
       1, 5, 3, 4, 5, 5, 0, 4, 2, 5, 3, 5, 5, 5, 2, 3, 3, 2, 0, 4, 4, 0,
       4, 5, 5, 3, 4, 3, 3, 4, 5, 2, 3, 3, 5, 3, 5, 4, 3, 2, 5, 5, 4, 5,
       5, 4, 5, 2, 4, 2, 4, 5, 2, 5, 4, 2, 4, 2, 1, 5, 4, 5, 2, 3, 0, 4,
       3, 4, 5, 4, 5, 2, 5, 1, 5, 5, 3, 3, 4, 5, 3, 5, 4, 5, 5, 5, 5, 2,
       3, 5, 4, 4, 5, 5, 5, 4, 5, 5, 4, 0, 2, 5, 1,

In [295]:
y_test

124     5
1687    3
1380    5
6       5
1422    5
       ..
841     4
220     2
1034    5
578     4
1184    3
Name: Index, Length: 508, dtype: int64

In [296]:
X_test

array([[-0.71474963,  1.3306313 , -0.94969956],
       [ 0.77258337, -0.67263626, -0.94969956],
       [-0.71474963,  0.43686577,  1.05296458],
       ...,
       [-0.90066625,  1.4539093 , -0.94969956],
       [ 0.40075012,  0.49850478, -0.94969956],
       [ 1.33033324,  0.06703176, -0.94969956]])

In [297]:
from sklearn.metrics import accuracy_score

In [298]:

acc=accuracy_score(y_pred,y_test)

In [299]:
acc

0.9940944881889764

In [300]:
model.predict(np.array([5.3,110,96]).reshape(1,3))

<IPython.core.display.Javascript object>

array([4], dtype=int64)

In [301]:
## np.array(scaler.transform(([[189,87,1]]))).reshape(1,3)

In [302]:
m=model.predict(scaler.transform(np.array([6.2,60,0]).reshape(1,3)))
print(m)

<IPython.core.display.Javascript object>

[0]


C:\Users\USER\anaconda3\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


In [303]:
m=model.predict(scaler.transform(np.array([5.2,139,1]).reshape(1,3)))
print(m)

<IPython.core.display.Javascript object>

[5]


C:\Users\USER\anaconda3\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


In [304]:
import pickle

In [305]:
pickle.dump(model, open("bmi_pickle.pkl", 'wb'))

In [306]:
m=model.predict(scaler.transform(np.array([11.9,65,1]).reshape(1,3)))
print(m)

<IPython.core.display.Javascript object>

[0]


C:\Users\USER\anaconda3\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"
